[package]
name = "learning_chat"
version = "0.1.0"
authors = ["marianne.goldin <marianne@transparentinc.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.1.0-beta"
get_if_addrs = "0.5.3"
ws = "0.9.1"
